<?php use Modules\Backend\Controllers\BaseController;
use Modules\Backend\Services\Utils;
 ?>
<title>Advertiser | Admin | Menu</title>
<section class="content-header">
	<h1>Advertiser</h1>
	<ol class="breadcrumb">
		<li><a href="/admin"><i class="fa fa-dashboard"></i> admin</a></li>
		<li><a href="/admin/advertiser">Advertiser</a></li>
		<li>Add</li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">						
		<div class="col-lg-12">
			<div class="box box-primary">
				<div class="body">
					<form class="form" id="formEdit" role="form" method="POST">
							<div class="row">
								<div class="col-lg-12">
									<div class="col-lg-4">
										<div class="form-group">
											<label>Name</label> 
											<input class="form-control" id="name" placeholder="Name" name="name" type="text" >
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
											<label>Local</label> 
											<input class="form-control" id="local" placeholder="local" name="local" type="text">
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
											<label>Href</label> 
											<input class="form-control" id="link" placeholder="href" name="link" type="text" >
										</div>
									</div>
								</div>
								<div class="col-lg-12">
									<div class="col-lg-4">
										<div class="form-group">
											<label>Width</label> 
											<input class="form-control" id="width" placeholder="Width" name="width" type="number" >
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
											<label>Height</label> 
											<input class="form-control" id="height" placeholder="Height" name="height" type="number" >
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
											<label>Possion</label> 
											<select id="pos" class="form-control " name='pos' >
												<option value="left">Left</option>
												<option value="right">Right</option>
											</select>
										</div>
									</div>
								</div>	
								<div class="col-lg-12">
									<div class="col-lg-4">
										<div class="form-group">
											<label>Status</label> 
											<select class="form-control" name='status'>
												<option value="1">Active</option>
												<option value="2">Inactive</option>
											</select>
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
											<label>Order</label> 
											<input class="form-control" id="sorted" placeholder="order" name="sorted" type="number" >
										</div>
									</div>
									<div class="col-lg-12">
										<div class="form-group">
											<label>Comment</label> 
											<textarea  class="form-control" id="comment" placeholder="Comment" name="comment" type="textarea" 
												rows="2" ></textarea>
										</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-lg-12">
									<div class="col-xs-12">
										<button type="submit" class="btn btn-primary col-md-offset-0" id="btnAdvancedSearch">Save</button>
									</div>
								<div class="col-lg-12">
							</div>
							
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	$(document).ready(function() {
		$crm.active_menu('configure', 'advertiser');
		$('#formEdit').validate({
			rules: {
				name:{minlength: 2, required:true},
				link: {required:true },
				order: { required:true },
				local: {required:true },   
				number: {required:true },
				height: {required:true },
				width: {required:true },
				parent :{required:true}
			},
			highlight: function(element) {
				$(element).closest('.form-group').removeClass('has-success').addClass('has-error');
			},
			unhighlight: function(element) {
				$(element).closest('.form-group').removeClass('has-error').addClass('has-success');
			},
			errorElement: 'span',
			errorClass: 'help-block',
			errorPlacement: function(error, element) {
				if(element.parent('.input-group').length) {
					error.insertAfter(element.parent());
				} else {
					error.insertAfter(element);
				}
			}    
		});
	});
</script>

