<?php use Modules\Frontend\Controllers\BaseController; ?>
<style>
        
        /* jssor slider bullet navigator skin 03 css */
        /*
        .jssorb03 div           (normal)
        .jssorb03 div:hover     (normal mouseover)
        .jssorb03 .av           (active)
        .jssorb03 .av:hover     (active mouseover)
        .jssorb03 .dn           (mousedown)
        */
        .jssorb03 {
            position: absolute;
        }
        .jssorb03 div, .jssorb03 div:hover, .jssorb03 .av {
            position: absolute;
            /* size of bullet elment */
            width: 21px;
            height: 21px;
            text-align: center;
            line-height: 21px;
            color: white;
            font-size: 12px;
            background: url('/images/img/b03.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb03 div { background-position: -5px -4px; }
        .jssorb03 div:hover, .jssorb03 .av:hover { background-position: -35px -4px; }
        .jssorb03 .av { background-position: -65px -4px; }
        .jssorb03 .dn, .jssorb03 .dn:hover { background-position: -95px -4px; }

        /* jssor slider arrow navigator skin 03 css */
        /*
        .jssora03l                  (normal)
        .jssora03r                  (normal)
        .jssora03l:hover            (normal mouseover)
        .jssora03r:hover            (normal mouseover)
        .jssora03l.jssora03ldn      (mousedown)
        .jssora03r.jssora03rdn      (mousedown)
        */
        .jssora03l, .jssora03r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 55px;
            height: 55px;
            cursor: pointer;
            background: url('/images/img/a03.png') no-repeat;
            overflow: hidden;
        }
        .jssora03l { background-position: -3px -33px; }
        .jssora03r { background-position: -63px -33px; }
        .jssora03l:hover { background-position: -123px -33px; }
        .jssora03r:hover { background-position: -183px -33px; }
        .jssora03l.jssora03ldn { background-position: -243px -33px; }
        .jssora03r.jssora03rdn { background-position: -303px -33px; }
    </style>
<title>Demo | Index</title>
<section class="content-header">
	<h1>Index <small><b id="Date" style="color: #F26230;"></b> <b id="hours"> </b><b id="point">:</b> <b id="min"> </b> <b id="point">:</b><b id="sec"> </b></small></h1>
	<ol class="breadcrumb">
		<li><a href="/"><i class="fa fa-dashboard"></i> Index</a></li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">	
		<div class="col-xs-1"></div>
		<div class="col-xs-1">
			<?php 
				$strQuery = "SELECT * FROM advertiser WHERE status = ".ACTIVE." ORDER BY sorted ASC";
				$result=$this->db->query($strQuery)->fetchAll();
				foreach($result as $val){
					if($val["pos"]==="left"){
						echo '<a href="'.$val["link"].'" >';
						echo '<img src="'.$val["local"].'" alt="'.$val["alt"].'" style="width:'.$val["width"].'px;height:'.$val["height"].'px;">';
						echo '</a>';
					}
				}
			?>
		</div>
		<div class="col-xs-8">
				<div class="col-lg-12">
					<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 809px; height: 150px; overflow: hidden; visibility: hidden;">
						<!-- Loading Screen -->
						<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
							<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
							<div style="position:absolute;display:block;background:url('/images/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
						</div>
						<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 809px; height: 150px; overflow: hidden;">
							<div style="display: none;">
								<img data-u="image" src="/images/img/005.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/006.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/011.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/013.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/014.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/019.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/020.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/021.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/022.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/024.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/025.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/027.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/029.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/030.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/031.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/030.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/034.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/038.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/039.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/043.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/044.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/047.jpg" />
							</div>
							<div style="display: none;">
								<img data-u="image" src="/images/img/050.jpg" />
							</div>
						
						
						</div>
						<!-- Bullet Navigator -->
						<div data-u="navigator" class="jssorb03" style="bottom:10px;right:10px;">
							<!-- bullet navigator item prototype -->
							<div data-u="prototype" style="width:21px;height:21px;">
								<div data-u="numbertemplate"></div>
							</div>
						</div>
						<!-- Arrow Navigator -->
						<span data-u="arrowleft" class="jssora03l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
						<span data-u="arrowright" class="jssora03r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
					</div>	
				</div>
				<div class="col-lg-12">
					<div class="box box-primary">
						<div class="row">	
							<div class="box-body table-responsive">
								<div class="col-xs-12">
									s
								</div>
							</div>
						</div>
					</div>
				</div>
			
		</div>
		<div class="col-xs-1">
			<?php 
				foreach($result as $val){
					if($val["pos"]==="right"){
						echo '<a href="'.$val["link"].'" >';
						echo '<img src="'.$val["local"].'" alt="'.$val["alt"].'" style="width:'.$val["width"].'px;height:'.$val["height"].'px;">';
						echo '</a>';
					}
				}
			?>
		</div>
		<div class="col-xs-1"></div>
	</div>
</section>
<!-- /.content -->
<script>
	$(document).ready(function() {
		$("#home").addClass("active");
		$crm.showDate();
 
            var jssor_1_options = {
              $AutoPlay: true,
              $AutoPlaySteps: 1,
              $SlideDuration: 200,
              $SlideWidth: 200,
              $SlideSpacing: 3,
              $Cols: 4,
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$,
                $Steps: 1
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $SpacingX: 1,
                $SpacingY: 1
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 809);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 20);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
	});	
</script>