<div class="form-box" id="login-box">
	<div class="header">Sign In</div>
	<form id="form" action="login" method="post" role="form" >
		<div class="body bg-gray">
			<div style="color: red;"><i><?php echo $error;?></i></div>
			<div class="form-group">
				<input type="text" name="user_name" class="form-control" placeholder="User ID" 
				value="<?php echo $user_name;?>" autofocus/>
			</div>
			<div class="form-group">
				<input type="password" name="password" class="form-control" placeholder="Password" 
				value="<?php echo $password;?>"/>
			</div>
		</div>
		<div class="footer">
			<input type="hidden" name="v" value="<?php echo $ajax;?>"/>
			<button type="submit" class="btn bg-olive btn-block">Sign me in</button>
		</div>
	</form>
</div>
<script>
	$('#form').validate({
	    rules: {
	        user_name:{  required:true },
	        password:{  required:true },
	    },
	    highlight: function(element) {
	        $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
	    },
	    unhighlight: function(element) {
	        $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
	    },
	    errorElement: 'span', errorClass: 'help-block'
	});
</script>