<?php use Modules\Backend\Controllers\BaseController; ?>
<title>Index | Admin | Home</title>
<section class="content-header">
	<h1>Index</h1>
	<ol class="breadcrumb">
		<li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
	</ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
			<div class="col-lg-4"> 
				<div class="box box-primary">
					<a href="/admin/menutop">
						<div class="box-body chart-responsive">
							<div class="col-xs-5"> 
								<h3>Menu Top</h3>
							</div>
							<div class="col-xs-7"> 
								<div class="col-xss-12">
									<div class="col-xs-12"> 
										<div class="col-xs-6"> 
											<h4>parent</h4>
										</div>
										<div class="col-xs-6"> 
											<h4><b><?php echo $total["menuParent"] ?></b></h4>
										</div>
									</div>
									<div class="col-xs-12"> 
										<div class="col-xs-6"> 
											<h4>Sub</h4>
										</div>
										<div class="col-xs-6"> 
											<h4><b><?php echo $total["menuSub"] ?></b></h4>
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</a>
				</div>
			</div>
			<div class="col-lg-4"> 
				<div class="box box-primary">
					<a href="/admin/advertiser">
						<div class="box-body chart-responsive">
							<div class="col-xs-6"> 
								<h3>Advertiser</h3>
							</div>
							<div class="col-xs-6"> 
								<h3><b><?php echo $total["advertiser"] ?></b></h3>
							</div>
						</div>
					</a>
				</div>
			</div>
	</div>
</section>

<script>
	$(document).ready(function() {
		$("#home").addClass("active");
		$('b').css('color','red');$('h3').css('color','black');
	});
</script>

