<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>Demo | Log in</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="/assets/backend/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/AdminLTE.css" rel="stylesheet" type="text/css" />
        
        <script src="/assets/backend/js/jquery.js"></script>
        <script src="/assets/backend/js/bootstrap.min.js" type="text/javascript"></script> 
		<script src="/assets/backend/js/jquery.validate.js"></script>
    </head>
    <body class="bg-black">
        <?php echo $this->getContent();?>             

    </body>
</html>