<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.png">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="/assets/backend/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/AdminLTE.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/bootstrap-duallistbox.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        <link href="/assets/backend/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
		<link href="/assets/backend/css/bootstrap-datepicker3.css" rel="stylesheet">
		<link href="/assets/backend/css/bootstrap-dialog.css" rel="stylesheet">
		<link href="/assets/backend/css/select2.css" rel="stylesheet">
		<link href="/assets/backend/css/mystyle.css" rel="stylesheet" />

		<script src="/assets/backend/js/jquery.js"></script>
        <!--<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>-->

        <script src="/assets/backend/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/assets/backend/js/AdminLTE/app.js" type="text/javascript"></script>
		<script src="/assets/backend/js/jquery.validate.js"></script>
		<script src="/assets/backend/js/plugins/daterangepicker/daterangepicker.js"></script>
		<script src="/assets/backend/js/bootstrap-datepicker.js"></script>
		<script src="/assets/backend/js/bootstrap-dialog.js"></script>
        
		<script src="/assets/backend/js/plugins/datatables/jquery.dataTables.js"></script>
		<script src="/assets/backend/js/plugins/datatables/dataTables.bootstrap.js"></script>
		
		<script src="/assets/backend/js/jquery.bootstrap-duallistbox.js"></script>
		<!-- <script src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1.1','packages':['corechart']}]}" type="text/javascript"></script>-->
   		<script src="/assets/backend/js/deverloper.js"></script>
		<script src="/assets/backend/js/jsapi.js"></script>
   		<script src="/assets/backend/js/jasny-bootstrap.js"></script>
   		<script src="/assets/backend/js/select2.js"></script>
		<script src="/assets/backend/js/bootstrap-paginator.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
   		
    </head>
    <body class="skin-blue fixed" > 
        <?php include_once 'topmenu.phtml';?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <?php include_once 'leftmenu.phtml';?>
            <aside class="right-side">    
            	<?php echo $this->getContent();?>      
            </aside>
        </div>
        
	<script type="text/javascript">
		$(document).ready(function() {
			$('.no-print').hide();
		});
	</script>


    </body>
</html>