<?php use Modules\Backend\Controllers\BaseController;
global $userSession ?>
<aside class="left-side sidebar-offcanvas">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<ul class="sidebar-menu">
			<li id="home"><a href="/admin/"> <i class="fa fa-home"></i><span>Home</span></a></li>
			<li id="configure" class="treeview">
				<a href="#"> <i class="fa fa-asterisk"></i> <span>Configure</span><i id="configureI" class="fa fa-angle-left pull-right"></i></a>
				<ul class="treeview-menu">
						<li id="menutop"><a href="/admin/menutop"><i class="fa fa-angle-double-right"></i>menu top</a></li>
						<li id="advertiser"><a href="/admin/advertiser"><i class="fa fa-angle-double-right"></i>Advertiser</a></li>
						<!--<li id="location"><a href="/admin/location"><i class="fa fa-angle-double-right"></i>Location</a></li>
						<li id="aptype"><a href="/admin/aptype"><i class="fa fa-angle-double-right"></i>AP Type</a></li>
						<li id="session"><a href="/admin/session"><i class="fa fa-angle-double-right"></i>Session</a></li>
						<li id="logintype"><a href="/admin/logintype"><i class="fa fa-angle-double-right"></i>Login Type</a></li>
						<li id="urlsplashpage"><a href="/admin/urlsplashpage"><i class="fa fa-angle-double-right"></i>Login Page</a></li>
						<li id="accesspoint"><a href="/admin/accesspoint"><i class="fa fa-angle-double-right"></i>AccessPoint</a></li>-->
 				</ul>
			</li><!-- /.li -->
		</ul>
	</section>
	<!-- /.sidebar -->
</aside>