<?php global $userSession?>
<header class="header">
	<a href="/admin" class="logo">Demo | test</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
		<!-- Sidebar toggle button-->
		<a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas"
			role="button"> <span class="sr-only">Toggle navigation</span> <span
			class="icon-bar"></span> <span class="icon-bar"></span> <span
			class="icon-bar"></span>
		</a>
		<div class="navbar-right">
			<ul class="nav navbar-nav">
				<li><a href="/">Site Index</a></li>
				<li><a href="/admin/profile"><i class="fa fa-user fa-fw"></i>Hi, <?php echo $userSession["full_name"]; ?></a></li>
				<li><a href="/admin/login/logout"><i class="fa fa-sign-out fa-fw"></i></a></li>
			</ul>
		</div>
	</nav>
</header>